---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="unstable"
    - image="debian"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="debian" tag="unstable"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "# out of `travis encrypt robertdebock:TOKEN-FROM-SLACK`"
  email: false
