---
# tasks file for microsoft_repository_keys

- name: Ensure required packages are present (Debian)
  ansible.builtin.package:
    name: "{{ microsoft_repository_keys_packages }}"
    state: present
  when:
    - ansible_os_family == "Debian"

- name: Ensure keyrings directory exists (Debian)
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when:
    - ansible_os_family == "Debian"

- name: Download Microsoft signing key (Debian)
  ansible.builtin.get_url:
    url: "{{ microsoft_repository_keys_url }}"
    dest: "/etc/apt/keyrings/microsoft.asc"
    mode: '0644'
  when:
    - ansible_os_family == "Debian"

- name: Convert Microsoft key to dearmored keyring (Debian)
  ansible.builtin.command:
    cmd: "gpg --dearmor -o {{ microsoft_repository_keys_keyring_path }} /etc/apt/keyrings/microsoft.asc"
    creates: "{{ microsoft_repository_keys_keyring_path }}"
  when:
    - ansible_os_family == "Debian"

- name: Set permissions on Microsoft keyring (Debian)
  ansible.builtin.file:
    path: "{{ microsoft_repository_keys_keyring_path }}"
    state: file
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_os_family == "Debian"

- name: Also install key into trusted.gpg.d for repos without signed-by (Debian)
  ansible.builtin.copy:
    src: "{{ microsoft_repository_keys_keyring_path }}"
    dest: "{{ microsoft_repository_keys_trusted_path }}"
    remote_src: true
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_os_family == "Debian"

- name: Add rpm key
  ansible.builtin.rpm_key:
    key: "{{ microsoft_repository_keys_url }}"
  when:
    - ansible_os_family == "RedHat"
